// metadataConfig.js

const metadataConfig = {
    home: {
        title: "Rol Drive | Global Chauffeur Services with Luxury Cars",
        description: "Experience Rol Drive's global chauffeur services with luxury cars. Enjoy sophistication, comfort, and impeccable service for your travels.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive: Elevating Travel with Global Chauffeur Services and Luxury Cars",
        ogDescription: "Discover Rol Drive's Global chauffeur services featuring luxury cars. Experience unparalleled comfort and elegance on every journey.",
        ogUrl: "https://www.roldrive.com/",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Discover Rol Drive's Global chauffeur services featuring luxury cars. Experience unparalleled comfort and elegance on every journey.",
        twitterTitle: "Rol Drive: Elevating Travel with Global Chauffeur Services and Luxury Cars",
        twitterSite: "https://www.roldrive.com/",
        twitterCreator: "@Rol_Drive",
    },

    airportTransfers: {
        title: "Book Best Airport Transfer to Start Your Journey | Rol Drive",
        description: "Start your journey right with Rol Drive's Best Airport Transfer. Enjoy punctual, comfortable, and hassle-free rides for a smooth travel experience.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/airport-transfers",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Book Premier Airport Transfers - Rol Drive",
        ogDescription: "Elevate your travel with Rol Drive's premier airport transfers. Experience luxury, punctuality, and comfort. Book now for a seamless journey!",
        ogUrl: "https://www.roldrive.com/airport-transfers",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Elevate your travel with Rol Drive's premier airport transfers. Experience luxury, punctuality, and comfort. Book now for a seamless journey!",
        twitterTitle: "Book Premier Airport Transfers - Rol Drive",
        twitterSite: "https://www.roldrive.com/airport-transfers",
        twitterCreator: "@Rol_Drive",
    },

    roadShows: {
        title: "Book Chauffeur Service for Roadshow Transfer | Rol Drive",
        description: "Secure Your Journey with Rol Drive's Premier Chauffeur Service for Roadshow Transfers. Book Now!",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/road-shows",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Book Your Roadshow Chauffeur Transfer with Rol Drive",
        ogDescription: "Experience roadshow with Rol Drive's chauffeur transfer service. Book now for stylish and reliable journey.",
        ogUrl: "https://www.roldrive.com/road-shows",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Experience roadshow with Rol Drive's chauffeur transfer service. Book now for stylish and reliable journey.",
        twitterTitle: "Book Your Roadshow Chauffeur Transfer with Rol Drive",
        twitterSite: "https://www.roldrive.com/road-shows",
        twitterCreator: "@Rol_Drive",
    },

    intercityRides: {
        title: "Intercity Chauffeur Service for Exciting Transfers | Rol Drive",
        description: "Travel with RolDrive’s intercity chauffeur service in luxury as we transfer you from one city to another. Safety and comfort being our top priority.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/intercity-rides",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "City-to-City Travel: Book Rol Drive Intercity Chauffeur Service",
        ogDescription: "Embark on a journey of comfort and style with Rol Drive Intercity Chauffeur Service. Seamless travel awaits!",
        ogUrl: "https://www.roldrive.com/intercity-rides",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Embark on a journey of comfort and style with Rol Drive Intercity Chauffeur Service. Seamless travel awaits!",
        twitterTitle: "City-to-City Travel: Book Rol Drive Intercity Chauffeur Service",
        twitterSite: "https://www.roldrive.com/intercity-rides",
        twitterCreator: "@Rol_Drive",
    },

    weddingChauffeur: {
        title: "Wedding Chauffeur Service in London | Rol Drive",
        description: "Elevate your wedding day with Rol Drive's elegant Wedding Chauffeur Service in London. Luxury transport tailored for your special occasion.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/wedding-chauffeur-service",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive: Your Wedding Chauffeur Service in London",
        ogDescription: "Experience luxury and elegance on your wedding day with Rol Drive's Chauffeur Service in London, ensuring seamless transportation for your special occasion.",
        ogUrl: "https://www.roldrive.com/wedding-chauffeur-service",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Experience luxury and elegance on your wedding day with Rol Drive's Chauffeur Service in London, ensuring seamless transportation for your special occasion.",
        twitterTitle: "Rol Drive: Your Wedding Chauffeur Service in London",
        twitterSite: "https://www.roldrive.com/wedding-chauffeur-service",
        twitterCreator: "@Rol_Drive",
    },

    corporateChauffeur: {
        title: "Book Your Corporate Chauffeur Service in London | Rol Drive",
        description: "Book your corporate chauffeur service in London with Rol Drive for a professional, reliable, and luxurious travel experience.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/corporate-chauffeur-service-london",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Book Corporate Chauffeur Service Hire in London | Rol Drive",
        ogDescription: "Premium Rol Drive's corporate chauffeur service in London. Elevate your business travel. Book your ride now!",
        ogUrl: "https://www.roldrive.com/corporate-chauffeur-service-london",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Premium Rol Drive's corporate chauffeur service in London. Elevate your business travel. Book your ride now!",
        twitterTitle: "Book Corporate Chauffeur Service Hire in London | Rol Drive",
        twitterSite: "https://www.roldrive.com/corporate-chauffeur-service-london",
        twitterCreator: "@Rol_Drive",
    },

    sightseeingChauffeur: {
        title: "Sightseeing Chauffeur Service in London | Rol Drive",
        description: "Discover London's iconic sights in luxury and comfort with Rol Drive's premium sightseeing chauffeur service. Enjoy a personalized and stress-free tour.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/sightseening-chauffeur-service",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive: Your Ultimate Sightseeing Chauffeur Service in London",
        ogDescription: "Experience London's iconic sights in luxury and comfort with Rol Drive's Sightseeing Chauffeur Service. Personalized tours with professional drivers await!",
        ogUrl: "https://www.roldrive.com/sightseening-chauffeur-service",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Experience London's iconic sights in luxury and comfort with Rol Drive's Sightseeing Chauffeur Service. Personalized tours with professional drivers await!",
        twitterTitle: "Rol Drive: Your Ultimate Sightseeing Chauffeur Service in London",
        twitterSite: "https://www.roldrive.com/sightseening-chauffeur-service",
        twitterCreator: "@Rol_Drive",
    },

    privateJetChauffeur: {
        title: "Private Jet Chauffeur Service in London | Rol Drive",
        description: "Arrive in style with Rol Drive's Private Jet Chauffeur Service in London. Enjoy seamless, luxurious transfers between your jet and destination.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/private-jet-chauffeur-service",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive: Premier Private Jet Chauffeur Service in London",
        ogDescription: "Enjoy seamless luxury travel with Rol Drive's Private Jet Chauffeur Service in London. Professional drivers ensure comfort and efficiency from jet to destination.",
        ogUrl: "https://www.roldrive.com/private-jet-chauffeur-service",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Enjoy seamless luxury travel with Rol Drive's Private Jet Chauffeur Service in London. Professional drivers ensure comfort and efficiency from jet to destination.",
        twitterTitle: "Rol Drive: Premier Private Jet Chauffeur Service in London",
        twitterSite: "https://www.roldrive.com/private-jet-chauffeur-service",
        twitterCreator: "@Rol_Drive",
    },

    eventTransportation: {
        title: "Event Transportation Services in London | Rol Drive",
        description: "Experience seamless event transportation in London with Rol Drive. Professional, reliable, and luxurious services for all your special occasions.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/event-transportation-services",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Professional Event Transportation in London with Rol Drive",
        ogDescription: "Make every event special with Rol Drive's Event Transportation Services in London. Enjoy seamless, luxury travel for any occasion with professional chauffeurs.",
        ogUrl: "https://www.roldrive.com/event-transportation-services",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Make every event special with Rol Drive's Event Transportation Services in London. Enjoy seamless, luxury travel for any occasion with professional chauffeurs.",
        twitterTitle: "Professional Event Transportation in London with Rol Drive",
        twitterSite: "https://www.roldrive.com/event-transportation-services",
        twitterCreator: "@Rol_Drive",
    },

    fleet: {
        title: "Chauffeur Driven Car Hire in London with Reliable Service | RolDrive",
        description: "Experience reliable luxury with RolDrive's Chauffeur Driven Car Hire in London. Enjoy professional, seamless service for all your transportation needs.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/fleet",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Travel in Class with RolDrive's Chauffeur Driven Car Hire in London",
        ogDescription: "Experience luxury and comfort with RolDrive's chauffeur driven car hire in London. Professional service and premium vehicles for a seamless journey.",
        ogUrl: "https://www.roldrive.com/fleet",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Experience luxury and comfort with RolDrive's chauffeur driven car hire in London. Professional service and premium vehicles for a seamless journey.",
        twitterTitle: "Travel in Class with RolDrive's Chauffeur Driven Car Hire in London",
        twitterSite: "https://www.roldrive.com/fleet",
        twitterCreator: "@Rol_Drive",
    },

    allServices: {
        title: "Daily Chauffeur Service London with Stress-Free Journey | RolDrive",
        description: "Enjoy a stress-free journey with RolDrive's daily chauffeur service in London. Professional, reliable, and luxurious travel every day.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/all-services",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Daily Chauffeur Service in London: Stress-Free Rides with RolDrive",
        ogDescription: "Enjoy a stress-free journey with RolDrive's daily chauffeur service in London, offering comfort, reliability, and luxury for your travel needs.",
        ogUrl: "https://www.roldrive.com/all-services",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Enjoy a stress-free journey with RolDrive's daily chauffeur service in London, offering comfort, reliability, and luxury for your travel needs.",
        twitterTitle: "Daily Chauffeur Service in London: Stress-Free Rides with RolDrive",
        twitterSite: "https://www.roldrive.com/all-services",
        twitterCreator: "@Rol_Drive",
    },

    login: {
        title: "Book Your Trip for Next Event | RolDrive",
        description: "Book your trip for the next event with RolDrive for a smooth, stylish, and reliable journey, ensuring you arrive in comfort and on time.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/login",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Book Your Next Event Journey with RolDrive for Ultimate Comfort",
        ogDescription: "Book your trip for your next event with RolDrive for a smooth, luxurious journey tailored to your needs, ensuring you arrive in style.",
        ogUrl: "https://www.roldrive.com/login",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Book your trip for your next event with RolDrive for a smooth, luxurious journey tailored to your needs, ensuring you arrive in style.",
        twitterTitle: "Book Your Next Event Journey with RolDrive for Ultimate Comfort",
        twitterSite: "https://www.roldrive.com/login",
        twitterCreator: "@Rol_Drive",
    },

    airportTransferLondon: {
        title: "Book Airport Transfers Chauffeur in London | Rol Drive",
        description: "Book your reliable airport transfers chauffeur in London with Rol Drive. Enjoy punctual service and comfortable rides for a stress-free journey.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/airport-transfers/airport-transfer-london",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Reliable Airport Transfers Chauffeur Service in London",
        ogDescription: "Book your airport transfers chauffeur in London with Rol Drive for seamless, reliable transportation. Enjoy comfort and efficiency from arrival to departure.",
        ogUrl: "https://www.roldrive.com/airport-transfers/airport-transfer-london",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Book your airport transfers chauffeur in London with Rol Drive for seamless, reliable transportation. Enjoy comfort and efficiency from arrival to departure.",
        twitterTitle: "Reliable Airport Transfers Chauffeur Service in London",
        twitterSite: "https://www.roldrive.com/airport-transfers/airport-transfer-london",
        twitterCreator: "@Rol_Drive",
    },

    airportTransferParis: {
        title: "Book Your Paris Airport Transfers With Comfort | Rol Drive",
        description: "Book Paris airport transfers with Rol Drive for a comfortable, luxurious ride to your destination, ensuring a smooth and stylish arrival.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/airport-transfers/airport-transfer-paris",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive: Premium Comfort for Paris Airport Transfers",
        ogDescription: "Book your Paris airport transfers with Rol Drive for a comfortable, luxurious, and stress-free journey to your destination with expert chauffeurs.",
        ogUrl: "https://www.roldrive.com/airport-transfers/airport-transfer-paris",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Book your Paris airport transfers with Rol Drive for a comfortable, luxurious, and stress-free journey to your destination with expert chauffeurs.",
        twitterTitle: "Rol Drive: Premium Comfort for Paris Airport Transfers",
        twitterSite: "https://www.roldrive.com/airport-transfers/airport-transfer-paris",
        twitterCreator: "@Rol_Drive",
    },

    airportTransferNewYork: {
        title: "Book Your Luxury Airport Transfers in New York | Rol Drive",
        description: "Seamless journeys begin with Rol Drive. Book your luxury airport transfers in New York for a stylish, comfortable, and stress-free travel experience.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/airport-transfers/airport-transfer-new-york",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Exclusive Ride with Rol Drive Luxury Airport Transfers in New York",
        ogDescription: "Embark on an exclusive journey with Rol Drive's luxury airport transfers in New York. Book your premium ride now.",
        ogUrl: "https://www.roldrive.com/airport-transfers/airport-transfer-new-york",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Embark on an exclusive journey with Rol Drive's luxury airport transfers in New York. Book your premium ride now.",
        twitterTitle: "Exclusive Ride with Rol Drive Luxury Airport Transfers in New York",
        twitterSite: "https://www.roldrive.com/airport-transfers/airport-transfer-new-york",
        twitterCreator: "@Rol_Drive",
    },

    airportTransferDubai: {
        title: "Book Airport Transfers From Dubai Airport | Rol Drive",
        description: "Book seamless and luxurious airport transfers from Dubai Airport with Rol Drive for a comfortable and stress-free travel experience.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/airport-transfers/airport-transfer-dubai",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Luxury Airport Transfers from Dubai Airport by Rol Drive",
        ogDescription: "Book airport transfers from Dubai Airport with Rol Drive for a seamless, luxurious, and stress-free journey to your destination with professional chauffeurs.",
        ogUrl: "https://www.roldrive.com/airport-transfers/airport-transfer-dubai",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Book airport transfers from Dubai Airport with Rol Drive for a seamless, luxurious, and stress-free journey to your destination with professional chauffeurs.",
        twitterTitle: "Luxury Airport Transfers from Dubai Airport by Rol Drive",
        twitterSite: "https://www.roldrive.com/airport-transfers/airport-transfer-dubai",
        twitterCreator: "@Rol_Drive",
    },

    airportTransferTokyo: {
        title: "Book Airport Chauffeur Transfer in Tokyo | Rol Drive",
        description: "Ensure a seamless arrival with Rol Drive's airport chauffeur transfer service in Tokyo. Experience comfort and efficiency from touchdown to destination.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/airport-transfers/tokyo-airport-transfer",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Book Airport Chauffeur Transfer in Tokyo with Rol Drive",
        ogDescription: "Book your seamless airport chauffeur transfer in Tokyo with Rol Drive. Enjoy reliable service and comfortable rides for a stress-free arrival or departure.",
        ogUrl: "https://www.roldrive.com/airport-transfers/tokyo-airport-transfer",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Book your seamless airport chauffeur transfer in Tokyo with Rol Drive. Enjoy reliable service and comfortable rides for a stress-free arrival or departure.",
        twitterTitle: "Book Airport Chauffeur Transfer in Tokyo with Rol Drive",
        twitterSite: "https://www.roldrive.com/airport-transfers/tokyo-airport-transfer",
        twitterCreator: "@Rol_Drive",
    },

    londonChauffeur: {
        title: "Luxury Chauffeur Service in London with Comfort Ride | Rol Drive",
        description: "Enjoy unparalleled comfort with Rol Drive's Luxury Chauffeur Service in London. Experience a smooth, elegant ride tailored to your needs.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/chauffeur-service-in-london",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive: Redefining Luxury Chauffeur Services in London",
        ogDescription: "Indulge in Rol Drive's Luxury Chauffeur Service in London. Enjoy a premium, comfortable ride with top-notch service and elegance.",
        ogUrl: "https://www.roldrive.com/chauffeur-service-in-london",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Indulge in Rol Drive's Luxury Chauffeur Service in London. Enjoy a premium, comfortable ride with top-notch service and elegance.",
        twitterTitle: "Rol Drive: Redefining Luxury Chauffeur Services in London",
        twitterSite: "https://www.roldrive.com/chauffeur-service-in-london",
        twitterCreator: "@Rol_Drive",
    },

    dubaiChauffeur: {
        title: "Premium Chauffeur Service in Dubai | Rol Drive",
        description: "Experience excellence with Rol Drive's premium chauffeur service in Dubai. Enjoy luxury travel with professional drivers and top-notch vehicles.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/chauffeur-service-in-dubai",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Discover Luxury: Premium Chauffeur Service in Dubai by Rol Drive",
        ogDescription: "Experience unparalleled luxury with Rol Drive's premium chauffeur service in Dubai. Exceptional service and exclusive vehicles for a memorable journey.",
        ogUrl: "https://www.roldrive.com/chauffeur-service-in-dubai",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Experience unparalleled luxury with Rol Drive's premium chauffeur service in Dubai. Exceptional service and exclusive vehicles for a memorable journey.",
        twitterTitle: "Discover Luxury: Premium Chauffeur Service in Dubai by Rol Drive",
        twitterSite: "https://www.roldrive.com/chauffeur-service-in-dubai",
        twitterCreator: "@Rol_Drive",
    },

    newYorkChauffeur: {
        title: "Best Chauffeur Service in New York | Rol Drive",
        description: "Experience the epitome of luxury and reliability with Rol Drive's best chauffeur service in New York. Enjoy comfort and style throughout your journey.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/chauffeur-service-in-new-york",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Experience Superiority: Best Chauffeur Service New York - Rol Drive",
        ogDescription: "Experience unparalleled luxury with Rol Drive's best chauffeur service in New York. Exceptional service and exclusive vehicles for a memorable journey.",
        ogUrl: "https://www.roldrive.com/chauffeur-service-in-new-york",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Experience unparalleled luxury with Rol Drive's best chauffeur service in New York. Exceptional service and exclusive vehicles for a memorable journey.",
        twitterTitle: "Experience Superiority: Best Chauffeur Service New York - Rol Drive",
        twitterSite: "https://www.roldrive.com/chauffeur-service-in-new-york",
        twitterCreator: "@Rol_Drive",
    },

    parisChauffeur: {
        title: "Luxury Chauffeur Service in Paris | Rol Drive",
        description: "Experience luxury with Rol Drive's chauffeur service in Paris. Enjoy impeccable service and prestigious vehicles for an elegant travel experience.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/chauffeur-service-in-paris",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Luxury Redefined: Rol Drive's Chauffeur Service in Paris",
        ogDescription: "Indulge in luxury with Rol Drive's chauffeur service in Paris. Enjoy impeccable service and prestigious vehicles for a sophisticated travel experience.",
        ogUrl: "https://www.roldrive.com/chauffeur-service-in-paris",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Indulge in luxury with Rol Drive's chauffeur service in Paris. Enjoy impeccable service and prestigious vehicles for a sophisticated travel experience.",
        twitterTitle: "Luxury Redefined: Rol Drive's Chauffeur Service in Paris",
        twitterSite: "https://www.roldrive.com/chauffeur-service-in-paris",
        twitterCreator: "@Rol_Drive",
    },

    tokyoChauffeur: {
        title: "Private Chauffeur Service in Tokyo | Rol Drive",
        description: "Enjoy exclusive travel with Rol Drive's private chauffeur service in Tokyo. Experience luxury, comfort, and personalized attention throughout your journey.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/chauffeur-service-in-tokyo",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Premium Comfort: Rol Drive's Private Chauffeur Service in Tokyo",
        ogDescription: "Enjoy exclusive comfort and privacy with Rol Drive's private chauffeur service in Tokyo. Premium vehicles and personalized attention for a luxurious journey.",
        ogUrl: "https://www.roldrive.com/chauffeur-service-in-tokyo",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Enjoy exclusive comfort and privacy with Rol Drive's private chauffeur service in Tokyo. Premium vehicles and personalized attention for a luxurious journey.",
        twitterTitle: "Premium Comfort: Rol Drive's Private Chauffeur Service in Tokyo",
        twitterSite: "https://www.roldrive.com/chauffeur-service-in-tokyo",
        twitterCreator: "@Rol_Drive",
    },

    hourlyChauffeur: {
        title: "Book Your Hourly Chauffeur Service with Comfort | Rol Drive",
        description: "Elevate your day with our hourly chauffeur service. Enjoy flexibility, comfort, and convenience on your terms. Your journey, your schedule. Book now!",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/hourly-chauffeur-service",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Book Premium Hourly Chauffeur Service | Rol Drive",
        ogDescription: "Experience luxury at your pace. Book Rol Drive's premium hourly chauffeur service for a tailored, comfortable, and stylish journey.",
        ogUrl: "https://www.roldrive.com/hourly-chauffeur-service",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Experience luxury at your pace. Book Rol Drive's premium hourly chauffeur service for a tailored, comfortable, and stylish journey.",
        twitterTitle: "Book Premium Hourly Chauffeur Service | Rol Drive",
        twitterSite: "https://www.roldrive.com/hourly-chauffeur-service",
        twitterCreator: "@Rol_Drive",
    },

    eventChauffeurLondon: {
        title: "Book Your Event Chauffeur Services in London | Rol Drive",
        description: "Make your event memorable with Rol Drive's premier chauffeur services in London. Experience elegance, reliability, and sophistication. Book now!",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/event-chauffeur-service-in-london",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Event Chauffeur Services in London | Rol Drive",
        ogDescription: "Elevate your event experience with Rol Drive's premier chauffeur services in London. Seamlessly blending luxury and reliability.",
        ogUrl: "https://www.roldrive.com/event-chauffeur-service-in-london",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Elevate your event experience with Rol Drive's premier chauffeur services in London. Seamlessly blending luxury and reliability.",
        twitterTitle: "Event Chauffeur Services in London | Rol Drive",
        twitterSite: "https://www.roldrive.com/event-chauffeur-service-in-london",
        twitterCreator: "@Rol_Drive",
    },

    executiveChauffeurLondon: {
        title: "Executive Chauffeur Service in London | Rol Drive",
        description: "Experience premium travel with Rol Drive's Executive Chauffeur Service in London, ensuring luxury, comfort, and reliability for your journey.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/executive-chauffeur-service-in-london",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive: Elevating Executive Chauffeur Services in London",
        ogDescription: "Experience luxury and professionalism with Rol Drive's Executive Chauffeur Service in London, offering premium comfort and reliability.",
        ogUrl: "https://www.roldrive.com/executive-chauffeur-service-in-london",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Experience luxury and professionalism with Rol Drive's Executive Chauffeur Service in London, offering premium comfort and reliability.",
        twitterTitle: "Rol Drive: Elevating Executive Chauffeur Services in London",
        twitterSite: "https://www.roldrive.com/executive-chauffeur-service-in-london",
        twitterCreator: "@Rol_Drive",
    },

    mercedesSprinterHireLondon: {
        title: "Mercedes Sprinter Chauffeur in London | Rol Drive",
        description: "Travel in style and comfort with Rol Drive's Mercedes Sprinter chauffeur service in London, offering luxury and reliability for every journey.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/mercedes-sprinter-hire-in-london",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive: Premium Mercedes Sprinter Chauffeur in London",
        ogDescription: "Travel in spacious luxury with Rol Drive's Mercedes Sprinter Chauffeur service in London, offering comfort, reliability, and style.",
        ogUrl: "https://www.roldrive.com/mercedes-sprinter-hire-in-london",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Travel in spacious luxury with Rol Drive's Mercedes Sprinter Chauffeur service in London, offering comfort, reliability, and style.",
        twitterTitle: "Rol Drive: Premium Mercedes Sprinter Chauffeur in London",
        twitterSite: "https://www.roldrive.com/mercedes-sprinter-hire-in-london",
        twitterCreator: "@Rol_Drive",
    },

    mercedesSClassLondon: {
        title: "Mercedes S Class Chauffeur Service in London | Rol Drive",
        description: "Book Rol Drive's Mercedes S Class Chauffeur Service in London for unmatched luxury, comfort, and elegance in your travel experience.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/mercedes-s-class-chauffeur-in-london",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive: Book Your Mercedes S Class Chauffeur Service Today",
        ogDescription: "Book Rol Drive’s Mercedes S Class Chauffeur Service in London for ultimate luxury, comfort, and elegance on your journey.",
        ogUrl: "https://www.roldrive.com/mercedes-s-class-chauffeur-in-london",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Book Rol Drive’s Mercedes S Class Chauffeur Service in London for ultimate luxury, comfort, and elegance on your journey.",
        twitterTitle: "Rol Drive: Book Your Mercedes S Class Chauffeur Service Today",
        twitterSite: "https://www.roldrive.com/mercedes-s-class-chauffeur-in-london",
        twitterCreator: "@Rol_Drive",
    },

    longDistanceChauffeur: {
        title: "Long Distance Chauffeur Service in London | Rol Drive",
        description: "Rol Drive offers top-notch long-distance chauffeur services in London, ensuring comfort and luxury for your journey. Book your ride today!",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/long-distance-chauffeur-service-in-london",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Long Distance Chauffeur Service in London with Rol Drive",
        ogDescription: "Travel long distances in style with Rol Drive’s chauffeur service in London. Enjoy comfort and luxury for all your extended journeys.",
        ogUrl: "https://www.roldrive.com/long-distance-chauffeur-service-in-london",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Travel long distances in style with Rol Drive’s chauffeur service in London. Enjoy comfort and luxury for all your extended journeys.",
        twitterTitle: "Long Distance Chauffeur Service in London with Rol Drive",
        twitterSite: "https://www.roldrive.com/long-distance-chauffeur-service-in-london",
        twitterCreator: "@Rol_Drive",
    },

    personalChauffeurLondon: {
        title: "Hire a Personal Chauffeur in London | RolDrive",
        description: "Hire your personal chauffeur in London with RolDrive for bespoke travel. Enjoy tailored service and luxury vehicles for a memorable experience.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/hire-a-personal-chauffeur-in-london",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Hire a Personal Chauffeur with RolDrive in London",
        ogDescription: "Hire a personal chauffeur in London with RolDrive for exclusive, tailored transportation. Enjoy luxury and convenience throughout your journey.",
        ogUrl: "https://www.roldrive.com/hire-a-personal-chauffeur-in-london",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Hire a personal chauffeur in London with RolDrive for exclusive, tailored transportation. Enjoy luxury and convenience throughout your journey.",
        twitterTitle: "Hire a Personal Chauffeur with RolDrive in London",
        twitterSite: "https://www.roldrive.com/hire-a-personal-chauffeur-in-london",
        twitterCreator: "@Rol_Drive",
    },

    fullDayChauffeurLondon: {
        title: "Full Day Chauffeur Hire in London with Comfort Journey | Rol Drive",
        description: "Experience luxury and convenience with Rol Drive's Full Day Chauffeur Hire in London, offering premium service and comfort for all your travel needs.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/full-day-chauffeur-hire",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Full Day Chauffeur Hire in London with Rol Drive",
        ogDescription: "Experience luxury travel in London with Rol Drive. Book chauffeur hire for a full day and indulge in seamless, premium transportation.",
        ogUrl: "https://www.roldrive.com/full-day-chauffeur-hire",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Experience luxury travel in London with Rol Drive. Book chauffeur hire for a full day and indulge in seamless, premium transportation.",
        twitterTitle: "Full Day Chauffeur Hire in London with Rol Drive",
        twitterSite: "https://www.roldrive.com/full-day-chauffeur-hire",
        twitterCreator: "@Rol_Drive",
    },

    mercedesVClassLondon: {
        title: "Mercedes V Class Chauffeur Service in London | Rol Drive",
        description: "Experience luxury travel with Mercedes V Class Chauffeur Service in London by Rol Drive. Comfort, style, and professionalism for your every journey.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/mercedes-v-class-london",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Experience Premium Travel: Mercedes V Class Chauffeur in London",
        ogDescription: "Mercedes V Class Chauffeur Service in London by Rol Drive offers luxury, comfort, and spacious travel for groups and families with professional chauffeurs.",
        ogUrl: "https://www.roldrive.com/mercedes-v-class-london",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Mercedes V Class Chauffeur Service in London by Rol Drive offers luxury, comfort, and spacious travel for groups and families with professional chauffeurs.",
        twitterTitle: "Experience Premium Travel: Mercedes V Class Chauffeur in London",
        twitterSite: "https://www.roldrive.com/mercedes-v-class-london",
        twitterCreator: "@Rol_Drive",
    },

    heathrowTransfer: {
        title: "Pick Up Heathrow Airport Transfer Chauffeur Service | Rol Drive",
        description: "Arrive in style and comfort with Rol Drive's pick-up airport transfer chauffeur service in Heathrow. Experience seamless luxury from touchdown. Book now!",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-transfer-heathrow",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive's Pick-Up Heathrow Airport Transfer Chauffeur Service",
        ogDescription: "Seamless arrivals at Heathrow with Rol Drive's pick-up airport transfer chauffeur service. Experience convenience, comfort, and reliability. Book your ride now!",
        ogUrl: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-transfer-heathrow",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Seamless arrivals at Heathrow with Rol Drive's pick-up airport transfer chauffeur service. Experience convenience, comfort, and reliability. Book your ride now!",
        twitterTitle: "Rol Drive's Pick-Up Heathrow Airport Transfer Chauffeur Service",
        twitterSite: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-transfer-heathrow",
        twitterCreator: "@Rol_Drive",
    },

    gatwickTransfer: {
        title: "Pick Up Gatwick Airport Transfers Chauffeur Service | Rol Drive",
        description: "Book RolDrive’s Gatwick Airport chauffeur service to get you to or from the airport in luxury and convenience. Our airport transfers at Gatwick make your journeys seamless.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-transfer-gatwick",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive's Pick-Up Gatwick Airport Transfers Chauffeur Service",
        ogDescription: "Experience seamless arrivals with Rol Drive's chauffeur service for pick-up Gatwick Airport transfers. Elevate your journey with luxury and comfort.",
        ogUrl: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-transfer-gatwick",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Experience seamless arrivals with Rol Drive's chauffeur service for pick-up Gatwick Airport transfers. Elevate your journey with luxury and comfort.",
        twitterTitle: "Rol Drive's Pick-Up Gatwick Airport Transfers Chauffeur Service",
        twitterSite: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-transfer-gatwick",
        twitterCreator: "@Rol_Drive",
    },

    londonCityTransfer: {
        title: "Book London City Airport Transfers | Rol Drive",
        description: "Seamless city arrivals begin with Rol Drive's London City Airport transfers. Experience comfort, reliability, and style. Book your journey with us now!",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-transfer-london-city",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive's London City Airport Transfers Await Your Booking",
        ogDescription: "Seamless journeys await with Rol Drive's London City Airport transfers. Experience luxury, reliability, and comfort. Book your ride now!",
        ogUrl: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-transfer-london-city",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Seamless journeys await with Rol Drive's London City Airport transfers. Experience luxury, reliability, and comfort. Book your ride now!",
        twitterTitle: "Rol Drive's London City Airport Transfers Await Your Booking",
        twitterSite: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-transfer-london-city",
        twitterCreator: "@Rol_Drive",
    },

    southendTransfer: {
        title: "Book Your Airport Transfers in Southend | Rol Drive",
        description: "Experience impeccable service with Rol Drive's airport transfers in Southend. Seamless, stylish, and reliable journeys await. Book your ride now!",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-london-southend",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Book Your Southend Airport Transfers with Rol Drive",
        ogDescription: "Experience seamless arrivals with Rol Drive's airport transfers in Southend. Book now for luxury, reliability, and comfort on your journey.",
        ogUrl: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-london-southend",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Experience seamless arrivals with Rol Drive's airport transfers in Southend. Book now for luxury, reliability, and comfort on your journey.",
        twitterTitle: "Book Your Southend Airport Transfers with Rol Drive",
        twitterSite: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-london-southend",
        twitterCreator: "@Rol_Drive",
    },

    stanstedTransfer: {
        title: "Hire London Stansted Airport Transfer | Rol Drive",
        description: "Effortless arrivals with Rol Drive's London Stansted Airport transfer. Elevate your journey with luxury, reliability, and style. Book your ride now!",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-london-stansted",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Hire London Stansted Airport Transfer with Rol Drive",
        ogDescription: "Experience effortless arrivals with Rol Drive's London Stansted Airport transfer service. Elevate your journey with luxury and comfort. Book now!",
        ogUrl: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-london-stansted",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Experience effortless arrivals with Rol Drive's London Stansted Airport transfer service. Elevate your journey with luxury and comfort. Book now!",
        twitterTitle: "Hire London Stansted Airport Transfer with Rol Drive",
        twitterSite: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-london-stansted",
        twitterCreator: "@Rol_Drive",
    },

    lutonTransfer: {
        title: "Luton Airport Transfer in London | Rol Drive",
        description: "Effortless arrivals with Rol Drive's Luton Airport Transfer in London. Experience comfort, reliability, and luxury. Book your journey with us now!",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-transfer-luton",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive's Exclusive Airport Transfer Service in London",
        ogDescription: "Arrive in style with Rol Drive's Luton Airport transfer service in London. Experience luxury and comfort on your journey. Book your ride now!",
        ogUrl: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-transfer-luton",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Arrive in style with Rol Drive's Luton Airport transfer service in London. Experience luxury and comfort on your journey. Book your ride now!",
        twitterTitle: "Rol Drive's Exclusive Airport Transfer Service in London",
        twitterSite: "https://www.roldrive.com/airport-transfers/airport-transfer-london/airport-transfer-luton",
        twitterCreator: "@Rol_Drive",
    },

    blog: {
        title: "RolDrive Blogs | Car Hire Blog | Travelling Blog",
        description: "At RolDrive’s car hire and travelling blog, we discuss the benefits of utilising a chauffeur driven vehicle for all your ground transportation needs.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://blog.roldrive.com/",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Journey Journal: Exploring the World with RolDrive",
        ogDescription: "Embark on a global odyssey through 'Journey Journal' by RolDrive, where travel stories, car hire insights, and wanderlust collide. Uncover your next adventure!",
        ogUrl: "https://blog.roldrive.com/",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Embark on a global odyssey through 'Journey Journal' by RolDrive, where travel stories, car hire insights, and wanderlust collide. Uncover your next adventure!",
        twitterTitle: "Journey Journal: Exploring the World with RolDrive",
        twitterSite: "https://blog.roldrive.com/",
        twitterCreator: "@Rol_Drive",
    },

    termsAndConditions: {
        title: "Terms and Conditions | Terms & Service | RolDrive",
        description: "RolDrive’s terms and conditions page for the ground transportation services that we provide. It is recommended that you read this page before booking our services.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/terms-and-conditions",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Driving with Confidence: Terms & Service at RolDrive",
        ogDescription: 'Explore with assurance through "Driving with Confidence: Terms & Service at RolDrive," ensuring transparency and reliability on your journey.',
        ogUrl: "https://www.roldrive.com/terms-and-conditions",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: 'Explore with assurance through "Driving with Confidence: Terms & Service at RolDrive," ensuring transparency and reliability on your journey.',
        twitterTitle: "Driving with Confidence: Terms & Service at RolDrive",
        twitterSite: "https://www.roldrive.com/terms-and-conditions",
        twitterCreator: "@Rol_Drive",
    },

    privacyPolicy: {
        title: "Privacy and Policy - Privacy & Terms | Rol Drive",
        description: "RolDrive’s privacy policies page mentions how we utilise your data. We recommend that you read this page before booking our services.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/privacy-policy",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "RolDrive Privacy and Policy - Privacy & Terms",
        ogDescription: "RolDrive’s privacy policies page that mentions how we utilise your data. We recommend that you read this page before booking our services.",
        ogUrl: "https://www.roldrive.com/privacy-policy",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "RolDrive’s privacy policies page that mentions how we utilise your data. We recommend that you read this page before booking our services.",
        twitterTitle: "RolDrive Privacy and Policy - Privacy & Terms",
        twitterSite: "https://www.roldrive.com/privacy-policy",
        twitterCreator: "@Rol_Drive",
    },

    gdprPolicy: {
        title: "General Data Protection Regulation (GDPR) and Policy | Rol Drive",
        description: "RolDrive’s GDPR policies page mentions how we utilise your data. We recommend that you read this page before booking our services.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/gdpr-policy",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive General Data Protection Regulation (GDPR) and Policy",
        ogDescription: "RolDrive’s GDPR policies page that mentions how we utilise your data. We recommend that you read this page before booking our services.",
        ogUrl: "https://www.roldrive.com/gdpr-policy",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "RolDrive’s GDPR policies page that mentions how we utilise your data. We recommend that you read this page before booking our services.",
        twitterTitle: "Rol Drive General Data Protection Regulation (GDPR) and Policy",
        twitterSite: "https://www.roldrive.com/gdpr-policy",
        twitterCreator: "@Rol_Drive",
    },

    becomeASupplier: {
        title: "Become a Supplier | Global Chauffeur Partner | Rol Drive",
        description: "Want to partner with RolDrive as a vehicle supplier? Feel free to contact us and learn more about our partnership program.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/become-a-supplier",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "RolDrive | Become a Supplier - Global Chauffeur Partner",
        ogDescription: "Want to partner with RolDrive as a ground transport supplier? Feel free to contact us and learn more about our partnership program.",
        ogUrl: "https://www.roldrive.com/become-a-supplier",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Want to partner with RolDrive as a ground transport supplier? Feel free to contact us and learn more about our partnership program.",
        twitterTitle: "RolDrive | Become a Supplier - Global Chauffeur Partner",
        twitterSite: "https://www.roldrive.com/become-a-supplier",
        twitterCreator: "@Rol_Drive",
    },

    faqs: {
        title: "Read FAQ about How to Book a Chauffeur Service | Rol Drive",
        description: "Get answers to all your questions on how to book a chauffeur service with Rol Drive. Explore our FAQ for a seamless and informed booking experience.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/faqs",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive's FAQ on Booking Chauffeur Services",
        ogDescription: "Find answers to your questions on booking chauffeur services with Rol Drive in our informative FAQ section. Your journey starts with knowledge.",
        ogUrl: "https://www.roldrive.com/faqs",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Find answers to your questions on booking chauffeur services with Rol Drive in our informative FAQ section. Your journey starts with knowledge.",
        twitterTitle: "Rol Drive's FAQ on Booking Chauffeur Services",
        twitterSite: "https://www.roldrive.com/faqs",
        twitterCreator: "@Rol_Drive",
    },

    aboutUs: {
        title: "About Rol Drive | Hire Your VIP Chauffeur With Comfort",
        description: "Rol Drive provides VIP chauffeur services, offering comfort and luxury for all your travel needs. Hire your VIP chauffeur today!",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/about-us",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Rol Drive: Comfort and Luxury in VIP Chauffeur Hire",
        ogDescription: "Rol Drive offers VIP chauffeur services, ensuring comfort and luxury. Hire your VIP chauffeur for a premium travel experience.",
        ogUrl: "https://www.roldrive.com/about-us",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Rol Drive offers VIP chauffeur services, ensuring comfort and luxury. Hire your VIP chauffeur for a premium travel experience.",
        twitterTitle: "Rol Drive: Comfort and Luxury in VIP Chauffeur Hire",
        twitterSite: "https://www.roldrive.com/about-us",
        twitterCreator: "@Rol_Drive",
    },

    contactUs: {
        title: "Contact Rol Drive | Call Us: +44 (0) 204 592 0966",
        description: "Get in touch with Rol Drive for premium chauffeur services. Call us at +44 (0) 204 592 0966 for bookings and inquiries.",
        robots: "index, follow",
        revisitAfter: "3 days",
        canonical: "https://www.roldrive.com/contact-us",
        ogLocale: "en_GB",
        ogType: "website",
        ogTitle: "Get in Touch with Rol Drive: Call +44 (0) 204 592 0966",
        ogDescription: "Reach out to Rol Drive for premium chauffeur services. Contact us at +44 (0) 204 592 0966 to book your luxury travel experience today.",
        ogUrl: "https://www.roldrive.com/contact-us",
        ogSiteName: "RolDrive",
        domainVerify: "5a85a1e146fef31be71b80439f963cde",
        twitterCard: "summary_large_image",
        twitterDescription: "Reach out to Rol Drive for premium chauffeur services. Contact us at +44 (0) 204 592 0966 to book your luxury travel experience today.",
        twitterTitle: "Get in Touch with Rol Drive: Call +44 (0) 204 592 0966",
        twitterSite: "https://www.roldrive.com/contact-us",
        twitterCreator: "@Rol_Drive",
    },


};

export default metadataConfig;
